# Generated by Django 4.1.1 on 2022-09-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_grocery_shoping', '0005_user_day_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='day_of_birth',
            field=models.DateField(null=True),
        ),
    ]
