# Generated by Django 4.1.1 on 2022-09-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_grocery_shoping', '0007_milk_and_meat_vegitable_rename_product_fruit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads'),
        ),
    ]
