# Generated by Django 4.1.1 on 2022-09-18 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_grocery_shoping', '0009_pages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pages',
        ),
    ]
