# Generated by Django 4.1.1 on 2022-09-19 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_grocery_shoping', '0010_delete_pages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_grocery_shoping.fruit')),
                ('milk_and_meat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_grocery_shoping.milk_and_meat')),
                ('vegitable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_grocery_shoping.vegitable')),
            ],
        ),
    ]
