# Generated by Django 4.1.1 on 2022-09-19 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_grocery_shoping', '0011_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
