# Generated by Django 4.1.1 on 2022-09-19 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_grocery_shoping', '0013_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fruit',
        ),
        migrations.DeleteModel(
            name='Milk_and_Meat',
        ),
        migrations.DeleteModel(
            name='Vegitable',
        ),
    ]
