# Generated by Django 4.1.1 on 2022-09-24 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_grocery_shoping', '0015_alter_cart_price_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Fruits', 'Fruits'), ('Vegetables', 'Vegitables'), ('Milk', 'Milk and Meat')], max_length=10),
        ),
    ]
